version: '3.3'
services:
  db:
    image: mysql:5.7
    container_name: dev-db3
    restart: always
    volumes:
      - my-db:/var/lib/mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
volumes:
  my-db: